# Generated by Django 4.1.2 on 2022-10-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('nuevo', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
