# Generated by Django 4.1.2 on 2022-11-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='apellido',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
